
GET http://localhost:3014/users

### Create User
POST http://localhost:3014/users
Content-Type: application/json

{
    "username":"Aga",
    "email":"aga@gmail.com",
    "password":"abs123456"
}

### Get all users
GET http://localhost:3014/users

### Get User with an ID
GET http://localhost:3014/users/1

### Remove User with an ID
DELETE http://localhost:3014/users/1

### Update User with an ID
PATCH http://localhost:3014/users/1
